import os
from pathlib import Path
import pandas as pd
import numpy as np

configfile : "config.yaml" #set index(reference fasta file) and data(path to paired end reads)

samples = pd.read_csv(config["samples"], index_col = "row ID", sep=',')

include: "rules/bowtie.smk"
include: "rules/samtools.smk"
include: "rules/qc.smk"
include: "rules/assembly.smk"
include: "rules/tree.smk"
include: "rules/sequence_variability.smk"

rule all:
    input:
        "variability/plot_variability.png",
        "tree/phylogenetic_tree.png"
